"""Increase active_token length

Revision ID: 10bceaa6d173
Revises: ac5b13ed82be
Create Date: 2023-12-26 23:02:29.188645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10bceaa6d173'
down_revision = 'ac5b13ed82be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('active_token',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('active_token',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    # ### end Alembic commands ###
