"""Add password_id to activity logs

Revision ID: 1877a9fc415b
Revises: 10bceaa6d173
Create Date: 2024-01-14 20:55:13.948029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1877a9fc415b'
down_revision = '10bceaa6d173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'passwords', ['password_id'], ['password_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('password_id')

    # ### end Alembic commands ###
