"""Added encryption key to Password model

Revision ID: 37aa8e02e5ce
Revises: 
Create Date: 2023-12-02 23:33:38.649725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37aa8e02e5ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_passwords')
    op.drop_table('activity_logs')
    with op.batch_alter_table('passwords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwords', schema=None) as batch_op:
        batch_op.drop_column('encryption_key')

    op.create_table('activity_logs',
    sa.Column('log_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('date_time', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='FK__activity___user___6383C8BA'),
    sa.PrimaryKeyConstraint('log_id', name='PK__activity__9E2397E0B60DF71D')
    )
    op.create_table('shared_passwords',
    sa.Column('shared_password_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('password_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shared_with_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_shared', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['password_id'], ['passwords.password_id'], name='FK__shared_pa__passw__66603565'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.user_id'], name='FK__shared_pa__share__6754599E'),
    sa.PrimaryKeyConstraint('shared_password_id', name='PK__shared_p__68117155D2359280')
    )
    # ### end Alembic commands ###
