"""Add snapshot fields to ActivityLog

Revision ID: 47a6989177c9
Revises: 1877a9fc415b
Create Date: 2024-01-15 01:00:08.453907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a6989177c9'
down_revision = '1877a9fc415b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_website_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('snapshot_website_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('snapshot_username', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('snapshot_password', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_column('snapshot_password')
        batch_op.drop_column('snapshot_username')
        batch_op.drop_column('snapshot_website_url')
        batch_op.drop_column('snapshot_website_name')

    # ### end Alembic commands ###
