"""Added active_token to User model

Revision ID: ac5b13ed82be
Revises: 7b0811e8bf07
Create Date: 2023-12-26 22:58:50.278497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'ac5b13ed82be'
down_revision = '7b0811e8bf07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_token', sa.String(length=255), nullable=True))
        batch_op.drop_column('token_valid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_valid', mssql.BIT(), autoincrement=False, nullable=True))
        batch_op.drop_column('active_token')

    # ### end Alembic commands ###
