"""Add snapshot fields to ActivityLog

Revision ID: b5f6e39200d0
Revises: 47a6989177c9
Create Date: 2024-01-15 01:15:36.185538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f6e39200d0'
down_revision = '47a6989177c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_decrypted_password', sa.String(length=255), nullable=True))
        batch_op.drop_column('snapshot_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_password', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.drop_column('snapshot_decrypted_password')

    # ### end Alembic commands ###
